#!/usr/bin/env python3
"""run_gcode_print.py - simulate the print a slicer prepared: the part's STL, the job's gcode, our print simulation.

    python3 demo/run_gcode_print.py --gcode job.gcode --stl part.stl [--mesh 1.5] [--layer 1.0] [--keep] [--out DIR]

The process comes from the gcode (tools/gcode_read.py): printed layer height, nozzle and bed temperature, the mean
deposition rate (deposited volume over the slicer's printing time) and the support settings (tree supports, threshold
angle, branch diameter, top gap). The ambient temperature is not in a gcode file and is assumed (--ambient). The
material is the library's published PLA record. The supports are generated by this simulator's own rule from those
settings, not copied from the toolpath, and their volume is compared with the volume the slicer printed.
What is compared at the end: size, layers, support volume and printing time against the slicer; the warp and the
residual stress are this simulator's prediction and have no measurement behind them for this part.
"""
import argparse, json, sys, tempfile, time
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tools"))
from mcptest import Client  # noqa: E402
from gcode_read import read as gcode_read  # noqa: E402


class SlowClient(Client):
    """the same client, patient: generating supports under a real part takes longer than the 20 s the tests allow"""
    def recv(self, timeout=1800.0):
        return super().recv(timeout)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--gcode", required=True)
    ap.add_argument("--stl", required=True)
    ap.add_argument("--mesh", type=float, default=1.5, help="element size, mm")
    ap.add_argument("--layer", type=float, default=1.0, help="simulation layer, mm (several printed layers at once)")
    ap.add_argument("--ambient", type=float, default=25.0, help="air temperature, degC (assumed: not in a gcode file)")
    ap.add_argument("--material", default="pla_fff")
    ap.add_argument("--no-supports", action="store_true")
    ap.add_argument("--keep", action="store_true")
    ap.add_argument("--out", default="")
    a = ap.parse_args()
    g = gcode_read(a.gcode)
    st = g["settings"]
    tmp = Path(tempfile.mkdtemp(prefix="nvgcode"))
    c = SlowClient(["--embedded", "--workspace", str(tmp / "ws"), "--allow-read", str(Path(a.stl).resolve().parent)])
    c.initialize()

    def call(name, args):
        sc = (c.call(name, args).get("result", {}) or {}).get("structuredContent") or {}
        if sc.get("ok") is not True:
            raise SystemExit(f"{name} refused: {json.dumps(sc.get('error'))[:900]}")
        return sc.get("value", {})

    call("project_create", {"name": "gcode_print", "description": f"the print of {Path(a.gcode).name}"})
    imp = call("geometry_import", {"path": str(Path(a.stl).resolve()), "units": "mm", "name": "part"})
    body = (imp.get("body") or imp)
    size = body.get("size_mm") or body.get("extent_mm") or (body.get("bounding_box") or {}).get("size_mm")
    print(f"part: {json.dumps(size)} mm from the STL; the gcode's part spans {g['box_mm']['part']['size']} mm")
    call("material_assign", {"body": "part", "material": a.material, "source": "user"})
    mesh = call("mesh_generate", {"element_size": f"{a.mesh:g} mm"})
    mesh = mesh.get("mesh", mesh)
    regions = (mesh.get("quality") or {}).get("face_connected_regions", 1)
    solid_cm3 = mesh.get("elements", 0) * a.mesh ** 3 / 1000
    print(f"mesh {a.mesh:g} mm: {mesh.get('elements')} elements, {solid_cm3:.2f} cm3 solid, {regions} connected piece(s); "
          f"the slicer deposits {g['volume_cm3']['part']} cm3 in the part ({100 * g['volume_cm3']['part'] / max(solid_cm3, 1e-9):.0f} % of solid)")
    if regions > 1:
        raise SystemExit(f"at {a.mesh:g} mm the part falls into {regions} pieces: thin members are lost and a loose piece cannot be "
                         "released from the bed. Use a smaller --mesh (the run stops here instead of failing at the release).")
    process = {
        "layer_height": f"{a.layer:g} mm", "printed_layer_height": f"{float(st['layer_height']):g} mm",
        "nozzle_temperature": f"{float(st['nozzle_temperature']):g} degC",
        "bed_temperature": f"{float(st.get('hot_plate_temp', st.get('textured_plate_temp', 60))):g} degC",
        "ambient_temperature": f"{a.ambient:g} degC",
        "deposition_rate": f"{g['mean_deposition_rate_mm3_s']:g} mm^3/s", "provenance": "user",
    }
    args = {"body": "part", "process": process, "label": f"from {Path(a.gcode).name}"}
    if not a.no_supports and st.get("enable_support", "1") not in ("0", "false"):
        r = float(st.get("tree_support_branch_diameter", 2)) / 2
        args["supports"] = {
            "type": "tree", "rule": "overhang", "critical_angle_deg": float(st.get("support_threshold_angle", 30)),
            "critical_angle_source": f"support_threshold_angle of {Path(a.gcode).name}",
            "trunk_radius": f"{r:g} mm", "branch_radius": f"{float(st.get('tree_support_tip_diameter', 0.8)) / 2:g} mm",
            "remove": True, "source": f"slicer settings embedded in {Path(a.gcode).name}", "provenance": "user",
        }
    t0 = time.time()
    job = call("mech_print_run", args)
    jid = job.get("job_id", "")
    print(f"print submitted as {jid}; process {json.dumps(process)}")
    status = {}
    while True:
        status = call("job_status", {"job_id": jid, "wait_seconds": 20})
        if status.get("state") not in ("queued", "running"):
            break
        print(f"  {status.get('stage', '')}  {100 * status.get('progress', 0):.0f} %  ({time.time() - t0:.0f} s)", flush=True)
    wall = time.time() - t0
    print(f"state {status.get('state')} after {wall:.0f} s")
    if status.get("state") != "succeeded":
        raise SystemExit(json.dumps(status.get("error"))[:900])
    summ = status.get("summary") or {}
    out = {"gcode": g, "process": process, "supports": args.get("supports"), "mesh_mm": a.mesh, "sim_layer_mm": a.layer,
           "wall_s": round(wall, 1), "summary": summ, "project": str(tmp)}
    if a.out:
        d = Path(a.out); d.mkdir(parents=True, exist_ok=True)
        (d / "drone_print_result.json").write_text(json.dumps(out, indent=1))
    print(json.dumps(summ, indent=1)[:3500])
    print(f"project kept in {tmp}" if a.keep else "")
    c.close() if hasattr(c, "close") else None
    if not a.keep:
        import shutil; shutil.rmtree(tmp, ignore_errors=True)


if __name__ == "__main__":
    main()
