/* embed.c - build helper: turns a data file into a C source file with a NUL-terminated byte array.
 *   embed <input> <output.c> <symbol> */
#include <stdio.h>
#include <stdlib.h>

int main(int argc, char **argv) {
    if (argc != 4) {
        fprintf(stderr, "usage: embed <input> <output.c> <symbol>\n");
        return 2;
    }
    FILE *in = fopen(argv[1], "rb");
    if (!in) {
        perror(argv[1]);
        return 1;
    }
    FILE *out = fopen(argv[2], "wb");
    if (!out) {
        perror(argv[2]);
        fclose(in);
        return 1;
    }
    fprintf(out, "/* generated by tools/embed.c from %s - do not edit */\n#include <stddef.h>\nconst char %s[] = {", argv[1], argv[3]);
    int c;
    size_t n = 0;
    while ((c = fgetc(in)) != EOF) {
        fprintf(out, "%s%d", n % 24 ? "," : (n ? ",\n" : "\n"), c);
        n++;
    }
    fprintf(out, "%s0};\nconst size_t %s_len = %zu;\n", n ? ",\n" : "\n", argv[3], n);
    int err = ferror(in) || ferror(out);
    fclose(in);
    if (fclose(out) != 0) err = 1;
    return err ? 1 : 0;
}
