/* Stored-field volume inspection and kernel water surface (labgpu.c, pass 3).
 *
 * The ray through each pixel crosses the field's box, from where it enters to where it leaves or meets the scene's
 * depth (a body inside the field hides what is behind it). Each sample takes the legend's colour of the stored value;
 * how strongly it shows grows with the value's size, and it is shaded by the field's own gradient, so that a wave front
 * or a hot core reads as a shape in 3D. Opacity, gradient shading, studio reflection and lighting are presentation,
 * documented in docs/lab/README.md; they are not optical properties of the field. Output: premultiplied, linear. */
static const char *volume_fs =
"#version 410 core\n"
"out vec4 frag;\n"
"uniform vec2 size, range;\n"
"uniform vec3 eye,right,up,forward,origin,extent,cell,lightDir;\n"
"uniform float focal,nearz,farz,fraction,cutPosition;\n"
"uniform int axis,flip,absoluteValue,logValue,waterSurface,walls,solidVolume; /* waterSurface: 1 water, 2 iso-surface of a field */\n"
"uniform sampler3D fieldTex,materialTex;\n"
"uniform sampler2D palette,sceneDepth;\n"
"float material(vec3 p){return texture(materialTex,(p-origin)/extent).r;}\n"
"float value(vec3 p){float v=texture(fieldTex,(p-origin)/extent).r;if(absoluteValue!=0)v=abs(v);if(logValue!=0)v=log(max(abs(v),1e-30))/log(10.);return v;}\n"
"vec3 color(float v){return pow(texture(palette,vec2(clamp((v-range.x)/max(range.y-range.x,1e-20),0.,1.),.5)).rgb,vec3(2.2));}\n"
"float strengthOf(float v){return (range.x<0.&&range.y>0.)?clamp(abs(v)/max(abs(range.x),abs(range.y)),0.,1.):clamp((v-range.x)/max(range.y-range.x,1e-20),0.,1.);}\n"
"float linearZ(float d){float A=(farz+nearz)/(farz-nearz),B=-2.*farz*nearz/(farz-nearz);return B/(2.*d-1.-A);}\n"
"void main(){\n"
"    vec3 ray=normalize(forward+right*(gl_FragCoord.x-size.x*.5)/focal+up*(gl_FragCoord.y-size.y*.5)/focal);\n"
"    vec3 low=origin,high=origin+extent;\n"
"    float cut=0.;\n"
"    if(axis>=0){cut=cutPosition;if(flip!=0)low[axis]=max(low[axis],cut);else high[axis]=min(high[axis],cut);}\n"
"    vec3 safeRay=ray;\n"
"    for(int k=0;k<3;k++)if(abs(safeRay[k])<1e-8)safeRay[k]=safeRay[k]<0.?-1e-8:1e-8;\n"
"    vec3 aa=(low-eye)/safeRay,bb=(high-eye)/safeRay;\n"
"    vec3 mn=min(aa,bb),mx=max(aa,bb);\n"
"    float enter=max(max(mn.x,mn.y),mn.z),leave=min(min(mx.x,mx.y),mx.z);\n"
"    enter=max(enter,nearz);\n"
"    float d=texture(sceneDepth,gl_FragCoord.xy/size).r;\n"
"    float boxLeave=leave;\n"
"    if(d<1.)leave=min(leave,linearZ(d)/dot(ray,forward));\n"
"    if(enter>=leave)discard;\n"
"    float span=max(max(extent.x,extent.y),extent.z);\n"
"    float stepSize=max(min(min(cell.x,cell.y),cell.z)*.35,length(extent)/1400.);\n"
"    vec3 position=eye+ray*(enter+stepSize*.01);\n"
"    vec4 sum=vec4(0.);\n"
"    vec3 L=normalize(lightDir);\n"
"    // The plane shows the interpolated stored field, not an invented boundary condition.\n"
"    if(axis>=0 && abs(position[axis]-cut)<stepSize*.025 && (waterSurface!=1 || material(position)>.5)){\n"
"        vec3 n=vec3(0.);n[axis]=flip!=0?-1.:1.;if(dot(n,ray)>0.)n=-n;\n"
"        sum=vec4(color(value(position))*(.80+.20*max(dot(n,L),0.)),1.);\n"
"        if(material(position)>=.5 && waterSurface==0)sum.rgb=vec3(.42,.45,.48);\n"
"    }else if(solidVolume!=0){\n"
"        // a body: its outside faces carry the stored field, lit by their normal\n"
"        vec3 n=vec3(0.);float best=1e30;\n"
"        for(int k=0;k<3;k++){float a=abs(position[k]-low[k]),b=abs(position[k]-high[k]);\n"
"            if(a<best){best=a;n=vec3(0.);n[k]=-1.;}if(b<best){best=b;n=vec3(0.);n[k]=1.;}}\n"
"        vec3 v=-ray,h=normalize(L+v);\n"
"        float hemi=.5+.5*n.z;vec3 amb=mix(vec3(.20,.19,.18),vec3(.50,.56,.66),hemi)*.62;\n"
"        sum=vec4(color(value(position))*(amb+vec3(1.,.96,.9)*.78*max(dot(n,L),0.))+vec3(.06)*pow(max(dot(n,h),0.),32.),1.);\n"
"    }else{\n"
"        // interleaved gradient noise (Jimenez 2014): an even jitter, so thin bright layers do not speckle\n"
"        float jitter=fract(52.9829189*fract(dot(gl_FragCoord.xy,vec2(.06711056,.00583715))));\n"
"        for(int i=0;i<2048;i++){\n"
"            float distance=enter+(float(i)+jitter)*stepSize;\n"
"            if(distance>leave || sum.a>.995)break;\n"
"            vec3 p=eye+ray*distance;\n"
"            float m=material(p),v=value(p);\n"
"            vec3 rgb=color(v);\n"
"            float strength=strengthOf(v);\n"
"            float alpha=1.-exp(-24.*strength*strength*stepSize/span);\n"
"            if(waterSurface!=0){\n"
"                if(m<.5)continue;\n"
"                float a=max(enter,distance-stepSize),b=distance;\n"
"                for(int j=0;j<8;j++){float mid=(a+b)*.5;if(material(eye+ray*mid)>.5)b=mid;else a=mid;}\n"
"                distance=(a+b)*.5;p=eye+ray*distance;rgb=color(value(p));\n"
"            }\n"
"            if(m>=.5){\n"
"                vec3 gradient=vec3(material(p+vec3(cell.x,0,0))-material(p-vec3(cell.x,0,0)),\n"
"                                   material(p+vec3(0,cell.y,0))-material(p-vec3(0,cell.y,0)),\n"
"                                   material(p+vec3(0,0,cell.z))-material(p-vec3(0,0,cell.z)));\n"
"                vec3 normal=dot(gradient,gradient)>1e-10?normalize(-gradient):-ray;\n"
"                if(dot(normal,ray)>0.)normal=-normal;\n"
"                vec3 halfVector=normalize(L-ray);\n"
"                if(waterSurface==2){\n"
"                    // an iso-surface of a computed field (vortex cores): coloured by the shown field, lit as a surface\n"
"                    float spec=pow(max(dot(normal,halfVector),0.),48.);\n"
"                    float hemi=.5+.5*normal.z;\n"
"                    rgb=rgb*(mix(vec3(.20,.19,.18),vec3(.50,.56,.66),hemi)*.62+vec3(1.,.96,.9)*.72*max(dot(normal,L),0.))+vec3(.12)*spec;\n"
"                }else if(waterSurface!=0){\n"
"                    float spec=pow(max(dot(normal,halfVector),0.),120.);\n"
"                    float fresnel=.02+.98*pow(1.-max(dot(normal,-ray),0.),5.);\n"
"                    // Studio reflection is a labelled appearance choice, not a simulated optical field.\n"
"                    rgb=rgb*(.45+.55*max(dot(normal,L),0.))+vec3(.20,.30,.40)*fresnel*.5+vec3(.9)*spec;\n"
"                }else rgb=vec3(.40,.43,.47)*(.30+.70*max(dot(normal,L),0.))+vec3(.5)*pow(max(dot(normal,halfVector),0.),40.);\n"
"                alpha=1.;\n"
"            }else if(alpha>.004){\n"
"                // shade by the gradient of the field's strength: its level surfaces lit like surfaces\n"
"                vec3 e=cell;\n"
"                vec3 gs=vec3(strengthOf(value(p+vec3(e.x,0,0)))-strengthOf(value(p-vec3(e.x,0,0))),\n"
"                             strengthOf(value(p+vec3(0,e.y,0)))-strengthOf(value(p-vec3(0,e.y,0))),\n"
"                             strengthOf(value(p+vec3(0,0,e.z)))-strengthOf(value(p-vec3(0,0,e.z))));\n"
"                float gl=length(gs);\n"
"                if(gl>1e-6){vec3 n=-gs/gl;if(dot(n,ray)>0.)n=-n;\n"
"                    float lam=max(dot(n,L),0.),sp=pow(max(dot(n,normalize(L-ray)),0.),24.);\n"
"                    float w=clamp(gl*6.,0.,1.);rgb=rgb*mix(1.,.55+.75*lam,w)+vec3(.25)*sp*w*strength;}\n"
"            }\n"
"            sum.rgb+=(1.-sum.a)*alpha*rgb;sum.a+=(1.-sum.a)*alpha;\n"
"        }\n"
"    }\n"
"    // a room's far walls, where the ray leaves the box unobstructed (a cutaway: the near walls are not drawn)\n"
"    if(walls!=0 && sum.a<.995 && leave>=boxLeave-1e-6*span){\n"
"        vec3 p=eye+ray*boxLeave,n=vec3(0.);float best=1e30;\n"
"        for(int k=0;k<3;k++){float a=abs(p[k]-origin[k]),b=abs(p[k]-origin[k]-extent[k]);\n"
"            if(a<best){best=a;n=vec3(0.);n[k]=1.;}if(b<best){best=b;n=vec3(0.);n[k]=-1.;}}\n"
"        vec3 q=(p-origin)/extent;float edge=min(min(min(q.x,1.-q.x),min(q.y,1.-q.y)),min(q.z,1.-q.z));\n"
"        vec3 base=n.z>.5?vec3(.07,.06,.055):vec3(.10,.10,.105);\n"
"        vec3 w=base*(.55+.45*max(dot(n,L),0.))*(.75+.25*smoothstep(0.,.08,edge));\n"
"        sum.rgb+=(1.-sum.a)*w;sum.a=1.;\n"
"    }\n"
"    if(sum.a<.002)discard;\n"
"    frag=sum;\n"
"}\n"
;
